baseURL = "/"
languageCode = "en-us"
paginate = 5
relativeURLs = true
theme = "hyde"
title = "QuickSite"
summaryLength = 12
enableEmoji = true

[[Menus.main]]
Name = "About"
URL = "/about"

[params]
description = "A website template."
disqusShortname = ""
googleAnalytics = ""
layoutReverse = true
theme = "hyde"
themeColor = "theme-base-0e"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
